export const cleanSVG = (txt = '') => txt
  .replace(/<text.*?<\/text>/g, '')
  .replace(/ class=".+?"/g, '')
  .replace(/ data-year=".+?"/g, '')
  .replace(/ stroke-dasharray=".+?"/g, '')
  .replace(/ stroke-dashoffset=".+?"/g, '')
  .replace(/ data-delay=".+?"/g, '')
  .replace(/ data-rotation=".+?"/g, '')
  .replace(/ data-g=".+?"/g, '')
  .replace(/ data-layer=".+?"/g, '')
  .replace(/ data-length=".+?"/g, '')
  .replace(/opacity: [01];/g, '')
  .replace(/transition: opacity.*?;/g, '')
  .replace(/transition: stroke-dashoffset.*?;/g, '')
